### ISSUE TITLE
2021.06.20DB2载入NPC提示载入错误

### ISSUE THREAD

**Issue by hanyuyang27** [Elem8100/MapleStoryDB2#2]
************* 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WinFormsApp1.Form1.LoadNpc()
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by Elem8100** [comment]
哪個版本?
台版最新v235沒問題
![npc](https://user-images.githubusercontent.com/49195287/123509486-5ee75200-d6a8-11eb-9d52-9a660d87df78.png)

**Comment by hanhao520** [comment]
![Uploading 360截图20210627002247827.jpg…]()

**Comment by hanyuyang27** [comment]
CMS最新V181
