### ISSUE TITLE
圖片不會自己消失

### ISSUE THREAD

**Issue by yuan-shen** [Elem8100/MapleStoryDB2#3]
隨便點一個選項出現圖片後
切到別的視窗
圖片還是會在
![image](https://user-images.githubusercontent.com/12084030/134859501-922992b6-0b4d-4c06-9957-b1dda028edbc.png)
![image](https://user-images.githubusercontent.com/12084030/134859607-bfe714f9-34b8-41bd-b105-dcb009571e74.png)
要自已用alt+tab關掉

**Comment by Elem8100** [comment]
要最小化
