### ISSUE TITLE
音樂功能僅讀取到部分內容

### ISSUE THREAD

**Issue by jh961202** [Elem8100/MapleStoryDB2#4]
如標題所述，嘗試使用最新release（2021-06-27）讀取TMS v238資料
選取音樂分頁後以載入wz方式讀取，結果僅讀取到Sound2.wz之資料（即BgmBT.img～PL_MMF.img部分）
![螢幕擷取畫面 2021-12-20 092258](https://user-images.githubusercontent.com/8479301/146698963-88852733-fcbd-465a-8784-437ffe75124d.png)

推測可能是TMS又修改資料存放方式造成，還請協助修復，謝謝！

**Comment by Elem8100** [comment]
已修復
https://github.com/Elem8100/WzComparerR2-Plus/releases
