### ISSUE TITLE
BUG回報

### ISSUE THREAD

**Issue by HolyBearTW** [Elem8100/MapleStoryDB2#5]
KMS 1.2.357版後無法載入，不確定是否為64位元或WZ架構變更的關係，再麻煩確認。

**Comment by Elem8100** [comment]
近期會發佈新版本

**Comment by Elem8100** [comment]
新版已發佈
https://github.com/Elem8100/WzComparerR2-Plus/releases

**Comment by HolyBearTW** [comment]
@Elem8100 所以MapleStoryDB2這個項目和WzComparerR2 Plus合併了嗎? 若是的話我會再和網友做宣傳告知~

**Comment by Elem8100** [comment]
是的,  所以DB2這個單獨項目以後不會再更新了
